include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for Visitor Message Board
LUCI_DESCRIPTION:=Luci app to manage the Visitor Message Board Docker container
LUCI_DEPENDS:=+docker

PKG_NAME:=luci-app-visitor-board
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
