#!/usr/bin/env python3
"""
build-packages.py - 为 OpenWrt 构建 IPK 和 APK 安装包

用法：在项目根目录执行
  python packaging/build-packages.py

产出：
  dist/
  ├── luci-app-visitor-board_aarch64_generic.ipk    (OpenWrt ≤24, opkg)
  ├── luci-app-visitor-board_x86_64.ipk             (OpenWrt ≤24, opkg)
  ├── luci-app-visitor-board_aarch64_generic.apk    (OpenWrt 25+, apk)
  └── luci-app-visitor-board_x86_64.apk             (OpenWrt 25+, apk)
"""

import os
import sys
import tarfile
import hashlib
import time
import struct
from pathlib import Path
from io import BytesIO

# 包元数据
PKG_NAME = "luci-app-visitor-board"
PKG_VERSION = "1.0.0"
PKG_RELEASE = "1"
PKG_TITLE = "LuCI app for Visitor Message Board"
PKG_DESC = "LuCI管理界面：容器状态监控、启停控制、日志查看、快捷链接"
PKG_MAINTAINER = "lan-zz"
PKG_LICENSE = "MIT"
PKG_DEPENDS = "docker"

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
DIST_DIR = PROJECT_ROOT / "dist"

# 源文件映射
LUCI_FILES = {
    "luasrc/controller/visitor-board.lua": "usr/lib/lua/luci/controller/visitor-board.lua",
    "luasrc/view/visitor-board/status.htm": "usr/lib/lua/luci/view/visitor-board/status.htm",
    "root/usr/bin/visitor-board.sh": "usr/bin/visitor-board.sh",
}


def create_tar_gz(files_map, source_base):
    """创建 tar.gz 包，返回 bytes。files_map: {源相对路径: 包内路径}"""
    buf = BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz", format=tarfile.GNU_FORMAT) as tar:
        for src_rel, dest_path in files_map.items():
            src_path = source_base / src_rel
            if not src_path.exists():
                print(f"  警告: 源文件不存在 {src_path}")
                continue
            info = tar.gettarinfo(str(src_path), arcname=dest_path)
            info.uid = 0
            info.gid = 0
            info.uname = ""
            info.gname = ""
            if dest_path.endswith(".sh"):
                info.mode = 0o755
            else:
                info.mode = 0o644
            with open(src_path, "rb") as f:
                tar.addfile(info, f)
    return buf.getvalue()


def create_ar_archive(members):
    """创建 ar 归档。members: [(name_bytes, bytes_data), ...]"""
    buf = BytesIO()
    # ar 签名
    buf.write(b"!<arch>\n")
    for name, data in members:
        # ar header: name(16) mtime(12) owner(6) group(6) mode(8) size(10) magic(2)
        mtime_str = str(int(time.time()))
        size_str = str(len(data))
        header = name.ljust(16, b' ') + b' '
        header += mtime_str.encode().ljust(12, b' ') + b' '
        header += b'0     0     '
        header += b'100644  '
        header += size_str.encode().ljust(10, b' ') + b'`\n'
        buf.write(header)
        buf.write(data)
        # ar 要求 2字节对齐
        if len(data) % 2 != 0:
            buf.write(b'\n')
    return buf.getvalue()


def write_text_tar_gz(text, arcname):
    """将纯文本内容打包为 tar.gz"""
    buf = BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz", format=tarfile.GNU_FORMAT) as tar:
        data = text.encode("utf-8")
        info = tarfile.TarInfo(name=arcname)
        info.size = len(data)
        info.uid = 0
        info.gid = 0
        info.uname = ""
        info.gname = ""
        info.mode = 0o644
        info.mtime = int(time.time())
        tar.addfile(info, BytesIO(data))
    return buf.getvalue()


def build_ipk(arch):
    """构建 IPK 包（OpenWrt ≤24，opkg）"""
    ipk_file = DIST_DIR / f"{PKG_NAME}_{arch}.ipk"
    print(f">>> [IPK] 构建 {arch} ...")

    # control
    control_text = f"""Package: {PKG_NAME}
Version: {PKG_VERSION}-{PKG_RELEASE}
Depends: {PKG_DEPENDS}
Source: {PKG_NAME}
License: {PKG_LICENSE}
Section: luci
Architecture: {arch}
Installed-Size: 0
Description: {PKG_TITLE}
 {PKG_DESC}
Maintainer: {PKG_MAINTAINER}
"""
    control_tar = write_text_tar_gz(control_text, "control")

    # data
    data_tar = create_tar_gz(LUCI_FILES, PROJECT_ROOT / "luci-app-visitor-board")

    # debian-binary
    debian_binary = b"2.0\n"

    # 打包
    ipk_data = create_ar_archive([
        (b"debian-binary", debian_binary),
        (b"control.tar.gz", control_tar),
        (b"data.tar.gz", data_tar),
    ])

    ipk_file.write_bytes(ipk_data)
    size_kb = len(ipk_data) / 1024
    print(f"<<< [IPK] {arch} 完成: {ipk_file.name} ({size_kb:.1f} KB)")


def build_apk(arch):
    """构建 APK 包（OpenWrt 25+，apk-tools）"""
    apk_file = DIST_DIR / f"{PKG_NAME}_{arch}.apk"
    print(f">>> [APK] 构建 {arch} ...")

    builddate = str(int(time.time()))

    buf = BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz", format=tarfile.GNU_FORMAT) as tar:
        # .PKGINFO 元数据
        pkginfo = f"""# Generated by build-packages.py
pkgname = {PKG_NAME}
pkgver = {PKG_VERSION}-r{PKG_RELEASE}
arch = {arch}
size = 0
pkgdesc = {PKG_TITLE} - {PKG_DESC}
url = https://github.com/lan-zz/visitor-message-board
builddate = {builddate}
license = {PKG_LICENSE}
maintainer = {PKG_MAINTAINER}
depend = {PKG_DEPENDS}
"""
        data = pkginfo.encode("utf-8")
        info = tarfile.TarInfo(name=".PKGINFO")
        info.size = len(data)
        info.uid = 0
        info.gid = 0
        info.uname = ""
        info.gname = ""
        info.mode = 0o644
        info.mtime = int(time.time())
        tar.addfile(info, BytesIO(data))

        # 文件
        source_base = PROJECT_ROOT / "luci-app-visitor-board"
        for src_rel, dest_path in LUCI_FILES.items():
            src_path = source_base / src_rel
            if not src_path.exists():
                continue
            fi = tar.gettarinfo(str(src_path), arcname=dest_path)
            fi.uid = 0
            fi.gid = 0
            fi.uname = ""
            fi.gname = ""
            fi.mode = 0o755 if dest_path.endswith(".sh") else 0o644
            with open(src_path, "rb") as f:
                tar.addfile(fi, f)

    apk_data = buf.getvalue()
    apk_file.write_bytes(apk_data)
    size_kb = len(apk_data) / 1024
    print(f"<<< [APK] {arch} 完成: {apk_file.name} ({size_kb:.1f} KB)")


def main():
    DIST_DIR.mkdir(parents=True, exist_ok=True)

    print("=" * 50)
    print(f"  构建 {PKG_NAME} 安装包")
    print(f"  版本: {PKG_VERSION}-{PKG_RELEASE}")
    print("=" * 50)
    print()

    arches = ["aarch64_generic", "x86_64"]

    for arch in arches:
        build_ipk(arch)
        build_apk(arch)
        print()

    print("=" * 50)
    print("  构建完成！")
    print("=" * 50)
    print()

    for f in sorted(DIST_DIR.iterdir()):
        size_kb = f.stat().st_size / 1024
        print(f"  {f.name:50s} {size_kb:6.1f} KB")

    print()
    print("文件说明：")
    print("  .ipk → OpenWrt ≤24  (opkg install xxx.ipk)")
    print("  .apk → OpenWrt 25+  (apk add --allow-untrusted xxx.apk)")
    print()
    print("安装示例：")
    print(f"  # OpenWrt ≤24 (aarch64)")
    print(f"  scp dist/{PKG_NAME}_aarch64_generic.ipk root@路由器:/tmp/")
    print(f"  opkg install /tmp/{PKG_NAME}_aarch64_generic.ipk")
    print()
    print(f"  # OpenWrt 25+ (aarch64)")
    print(f"  scp dist/{PKG_NAME}_aarch64_generic.apk root@路由器:/tmp/")
    print(f"  apk add --allow-untrusted /tmp/{PKG_NAME}_aarch64_generic.apk")


if __name__ == "__main__":
    main()
